### ISSUE TITLE
ERROR: mailcoach.actions.prepare_subject

### ISSUE THREAD

**Issue by StanBarrows** [spatie/mailcoach-support#166]
Hello everyone,

I'm not able to send campaigns anymore. When I check out the log files I can see the following errors. I'm using the package installer.

![image](https://user-images.githubusercontent.com/10268813/80099633-10ec3100-856f-11ea-8b3b-a06aeae13e30.png)

I've tried to send test-emails within the configuration and this worked perfectly. Tried different lists or created several campaigns but without luck so far.

### Error
```
[2020-04-23 12:27:24] production.ERROR: The class currently specified in the `mailcoach.actions.prepare_subject` key '' should be or extend `Spatie\Mailcoach\Actions\Campaigns\PrepareSubjectAction`. {"exception":"[object] (Spatie\\Mailcoach\\Exceptions\\InvalidConfig(code: 0): The class currently specified in the `mailcoach.actions.prepare_subject` key '' should be or extend `Spatie\\Mailcoach\\Actions\\Campaigns\\PrepareSubjectAction`. at /home/forge/mailcoach.**DOMAIN**ch/vendor/spatie/laravel-mailcoach/src/Exceptions/InvalidConfig.php:11)
[stacktrace]
```

```
#0 /home/forge/mailcoach.**DOMAIN**..ch/vendor/spatie/laravel-mailcoach/src/Support/Config.php(14): Spatie\\Mailcoach\\Exceptions\\InvalidConfig::invalidAction()
#1 /home/forge/mailcoach.**DOMAIN**..ch/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/SendCampaignAction.php(33): Spatie\\Mailcoach\\Support\\Config::getActionClass()
#2 /home/forge/mailcoach.**DOMAIN**..ch/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/SendCampaignAction.php(24): Spatie\\Mailcoach\\Actions\\Campaigns\\SendCampaignAction->prepareSubject()
#3 /home/forge/mailcoach.**DOMAIN**..ch/vendor/spatie/laravel-mailcoach/src/Jobs/SendCampaignJob.php(37): Spatie\\Mailcoach\\Actions\\Campaigns\\SendCampaignAction->execute()
#4 [internal function]: Spatie\\Mailcoach\\Jobs\\SendCampaignJob->handle()
#5 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#6 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure()
#8 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#9 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
#10 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#11 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#12 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#14 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
#15 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#16 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
#18 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#19 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#20 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Jobs\\Job->fire()
#21 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\\Queue\\Worker->process()
#22 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\\Queue\\Worker->runJob()
#23 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
#24 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#25 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#26 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#27 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#28 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure()
#30 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#31 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
#32 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#33 /home/forge/mailcoach.**DOMAIN**..ch/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#34 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#35 /home/forge/mailcoach.**DOMAIN**.ch/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run()
#36 /home/forge/mailcoach.medicalinformatics.ch/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#37 /home/forge/mailcoach.medicalinformatics.ch/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#38 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#39 /home/forge/mailcoach.**DOMAIN**..ch/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#40 /home/forge/mailcoach.medicalinformatics.ch/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#41 {main}
"} 
```

### Composer require

```
        "php": "^7.4",
        "ext-json": "*",
        "aws/aws-sdk-php": "^3.121",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.5",
        "laravel/framework": "^7.0",
        "laravel/horizon": "^4.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "spatie/laravel-flash": "^1.5",
        "spatie/laravel-json-api-paginate": "^1.7",
        "spatie/laravel-mailcoach": "^2.0",
        "spatie/laravel-mailcoach-mailgun-feedback": "^2.0",
        "spatie/laravel-mailcoach-monaco": "^1.0",
        "spatie/laravel-mailcoach-postmark-feedback": "^2.0",
        "spatie/laravel-mailcoach-sendgrid-feedback": "^2.0",
        "spatie/laravel-mailcoach-ses-feedback": "^2.0",
        "spatie/laravel-mailcoach-unlayer": "^1.0",
        "spatie/laravel-query-builder": "^2.8",
        "spatie/laravel-welcome-notification": "^2.0",
        "spatie/valuestore": "^1.2",
        "wildbit/swiftmailer-postmark": "^3.1"
```

### Server
PHP 7.4.4 (cli) (built: Mar 20 2020 13:47:45)

Best regards
Stan

**Comment by freekmurze** [comment]
Can you read trough this issue and try this solutions that are proposed there? https://github.com/spatie/mailcoach-support/issues/145

**Comment by StanBarrows** [comment]
Perfect thanks!

I was updating from v2.2.* to 2.7.* and the following lines were missing within the config file.

```
'prepare_subject' => \Spatie\Mailcoach\Actions\Campaigns\PrepareSubjectAction::class,
'personalize_subject' => \Spatie\Mailcoach\Actions\Campaigns\PersonalizeSubjectAction::class,
```

**Comment by RicardoRamirezR** [comment]
I had the same error. But Mailcouch did not warn about it. Shall Mailcoach send some sort of feedback
