### ISSUE TITLE
Unable to locate a class or view for component [icon-label]

### ISSUE THREAD

**Issue by beberlei** [spatie/mailcoach-support#269]
I upgraded my Mailcoach v2 app to v3 by copying over the composer.json from the `spatie/mailcoach` repository, running `composer update` and applying everything from the upgrading guide, including the database migration. The mailcoach app itself works mostly, but when I go to the user profile page, or the users list or other laravel framework provided user pages I get this error:

```
[2020-10-30 18:00:44] production.ERROR: Unable to locate a class or view for component [icon-label]. {"userId":1,"exception":"[object] (InvalidArgumentException(code: 0): Unable to locate a class or view for component [icon-label]. at /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php:274)
[stacktrace]
#0 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php(210): Illuminate\\View\\Compilers\\ComponentTagCompiler->componentClass()
#1 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php(195): Illuminate\\View\\Compilers\\ComponentTagCompiler->componentString()
#2 [internal function]: Illuminate\\View\\Compilers\\ComponentTagCompiler->Illuminate\\View\\Compilers\\{closure}()
#3 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php(190): preg_replace_callback()
#4 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php(88): Illuminate\\View\\Compilers\\ComponentTagCompiler->compileSelfClosingTags()
#5 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php(75): Illuminate\\View\\Compilers\\ComponentTagCompiler->compileTags()
#6 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(329): Illuminate\\View\\Compilers\\ComponentTagCompiler->compile()
#7 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(229): Illuminate\\View\\Compilers\\BladeCompiler->compileComponentTags()
#8 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(150): Illuminate\\View\\Compilers\\BladeCompiler->compileString()
#9 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(55): Illuminate\\View\\Compilers\\BladeCompiler->compile()
#10 /var/www/mailcoach/mailcoach/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get()
#11 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get()
#12 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#13 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#14 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Http/Response.php(62): Illuminate\\View\\View->render()
#15 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Http/Response.php(34): Illuminate\\Http\\Response->setContent()
#16 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Routing/Router.php(765): Illuminate\\Http\\Response->__construct()
#17 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router::toResponse()
#18 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\\Routing\\Router->prepareResponse()
#19 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#20 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#22 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#24 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#26 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#28 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#29 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#31 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#33 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Pipeline\\Pipeline->then()
#35 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack()
#36 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\\Routing\\Router->runRoute()
#37 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->dispatchToRoute()
#38 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#39 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#40 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#42 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#44 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#46 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#48 /var/www/mailcoach/mailcoach/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#50 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#52 /var/www/mailcoach/mailcoach/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#53 /var/www/mailcoach/mailcoach/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
```

**Comment by beberlei** [comment]
My mistake, I needed to merge tons of additional changes from `spatie/mailcoach` into my own fork. Doing that fixes it.
