### ISSUE TITLE
Placeholders are not working in web view

### ISSUE THREAD

**Issue by MianSaleem** [spatie/mailcoach-support#32]
Hello,

Is there any option so that placeholders should work in web view url too?

In my list, some subscribers don't have first_name and last_name. Sending campaign to subscribers with no first_name is failing as I have used `::subscriber.first_name::` in the template. Is there any way to send email even if the subscriber don't have first_name by leaving it blank?

**Comment by freekmurze** [comment]
The web view isn't personalised, so placeholders that concern the subscriber aren't replaced there.

> In my list, some subscribers don't have first_name and last_name. Sending campaign to subscribers with no first_name is failing as I have used ::subscriber.first_name:: in the template. Is there any way to send email even if the subscriber don't have first_name by leaving it blank?

In this scenario the `::subscriber.first_name::` should have been replace by a blank. Could you share the exception and trace?

**Comment by MianSaleem** [comment]
Yes, please refer to error log below
```
[2020-02-03 06:42:43] production.ERROR: Array to string conversion {"exception":"[object] (ErrorException(code: 0): Array to string conversion at /home/xxxxx/xxxxx/vendor/spatie/laravel-mailcoach/src/Support/Replacers/Concerns/ReplacesModelAttributes.php:12)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/xxxxx/xxxxx/vendor/spatie/laravel-mailcoach/src/Support/Replacers/Concerns/ReplacesModelAttributes.php(12): preg_replace_callback()
#2 /home/xxxxx/xxxxx/vendor/spatie/laravel-mailcoach/src/Support/Replacers/SubscriberReplacer.php(24): Spatie\\Mailcoach\\Support\\Replacers\\SubscriberReplacer->replaceModelAttributes()
#3 /home/xxxxx/xxxxx/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/PersonalizeHtmlAction.php(21): Spatie\\Mailcoach\\Support\\Replacers\\SubscriberReplacer->replace()
#4 [internal function]: Spatie\\Mailcoach\\Actions\\Campaigns\\PersonalizeHtmlAction->Spatie\\Mailcoach\\Actions\\Campaigns\\{closure}()
#5 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Support/Collection.php(890): array_reduce()
#6 /home/xxxxx/xxxxx/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/PersonalizeHtmlAction.php(21): Illuminate\\Support\\Collection->reduce()
#7 /home/xxxxx/xxxxx/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/SendMailAction.php(33): Spatie\\Mailcoach\\Actions\\Campaigns\\PersonalizeHtmlAction->execute()
#8 /home/xxxxx/xxxxx/vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/SendMailAction.php(16): Spatie\\Mailcoach\\Actions\\Campaigns\\SendMailAction->sendMail()
#9 /home/xxxxx/xxxxx/vendor/spatie/laravel-mailcoach/src/Jobs/SendMailJob.php(44): Spatie\\Mailcoach\\Actions\\Campaigns\\SendMailAction->execute()
#10 [internal function]: Spatie\\Mailcoach\\Jobs\\SendMailJob->handle()
#11 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#12 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#16 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#17 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#18 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#20 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
#21 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#22 /home/xxxxx/xxxxx/vendor/spatie/laravel-rate-limited-job-middleware/src/RateLimited.php(154): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiter.php(90): Spatie\\RateLimitedMiddleware\\RateLimited->Spatie\\RateLimitedMiddleware\\{closure}()
#24 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiterBuilder.php(113): Illuminate\\Redis\\Limiters\\DurationLimiter->block()
#25 /home/xxxxx/xxxxx/vendor/spatie/laravel-rate-limited-job-middleware/src/RateLimited.php(157): Illuminate\\Redis\\Limiters\\DurationLimiterBuilder->then()
#26 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Spatie\\RateLimitedMiddleware\\RateLimited->handle()
#27 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
#29 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#30 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call()
#31 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(368): Illuminate\\Queue\\Jobs\\Job->fire()
#32 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\\Queue\\Worker->process()
#33 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(267): Illuminate\\Queue\\Worker->runJob()
#34 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->runNextJob()
#35 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#36 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#37 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#38 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#39 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#40 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#41 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#42 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(201): Illuminate\\Container\\Container->call()
#43 /home/xxxxx/xxxxx/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#44 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Console/Command.php(188): Symfony\\Component\\Console\\Command\\Command->run()
#45 /home/xxxxx/xxxxx/vendor/symfony/console/Application.php(1012): Illuminate\\Console\\Command->run()
#46 /home/xxxxx/xxxxx/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand()
#47 /home/xxxxx/xxxxx/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#48 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#49 /home/xxxxx/xxxxx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#50 /home/xxxxx/xxxxx/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#51 {main}
```

**Comment by freekmurze** [comment]
Thanks for this info.

I've just release `v1.4.2` in which this bug is fixed.
