### ISSUE TITLE
More database columns are too short

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#49]
I just got 2 more exceptions:

```
Illuminate\Database\QueryException, Code: 22001: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1 (SQL: insert into `mailcoach_campaign_links` (`campaign_id`, `url`, `updated_at`, `created_at`) values (1, https://myproject.com/unsubscribe?unsub=eyJpdiI6Ill6ODRTdEorVnNmMHVpUTRvS25DYlE9PSIsInZhbHVlIjoiWW9tV0JwVlpsejZ4M3huOGR2NndHWGdGbFpUK2VrUDN0akllbit5SkZ1bm9oYTRuU0czWW9YdUtxVlNYMng2NDBNZk4zckFCcG1IU3VKYXNaOGZoODc2N0hJNTloaitVcGd6eFNpczlWV2daU2Jscllqa3AxN3FucFNLQWRtZ20iLCJtYWMiOiJiMjNlNTIzMjQ3ZjQ3OTM3ZWQ3NmQ0NjkzZmQ4MTE4NjRmMDExMWUxYjhmOWIzNzRkZDI2YWM2MjMyYTRjZGI3In0%3D%2C+2020-02-07+17%3A21%3A11%2C+2020-02-07+17%3A21%3A11%29%29
```
and
```
PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1 in /apps/myproject/releases/24/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121
Stack trace:
#0 /apps/myproject/releases/24/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(121): PDOStatement->execute()
#1 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Connection.php(463): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback()
#4 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Connection.php(464): Illuminate\Database\Connection->run()
#5 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\Database\Connection->statement()
#6 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#7 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2672): Illuminate\Database\Query\Processors\Processor->processInsertGetId()
#8 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1366): Illuminate\Database\Query\Builder->insertGetId()
#9 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(839): Illuminate\Database\Eloquent\Builder->__call()
#10 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(804): Illuminate\Database\Eloquent\Model->insertAndSetId()
#11 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(667): Illuminate\Database\Eloquent\Model->performInsert()
#12 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(438): Illuminate\Database\Eloquent\Model->save()
#13 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}()
#14 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(439): tap()
#15 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->firstOrCreate()
#16 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1620): Illuminate\Database\Eloquent\Model->forwardCallTo()
#17 /apps/myproject/releases/24/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1632): Illuminate\Database\Eloquent\Model->__call()
#18 /apps/myproject/releases/24/vendor/spatie/laravel-mailcoach/src/Models/Send.php(147): Illuminate\Database\Eloquent\Model::__callStatic()
#19 /apps/myproject/releases/24/vendor/spatie/laravel-mailcoach-ses-feedback/src/SesEvents/Click.php(16): Spatie\Mailcoach\Models\Send->registerClick()
```

**Comment by freekmurze** [comment]
Thanks for reporting I've changed the `url` column of the `mailcoach_campaign_links` table  in the default mailcoach migrations.

```
$table->string('url', 2048);
``

**Comment by ryancwalsh** [comment]
Thanks!

I'll run this migration:

```
public function up() {
        Schema::table('mailcoach_campaign_links', function (Blueprint $table) {
            $table->string('url', 2048)->change(); //https://github.com/spatie/mailcoach-support/issues/49#issuecomment-583609080
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::table('mailcoach_campaign_links', function (Blueprint $table) {
            $table->string('url')->change();
        });
    }
```
