### ISSUE TITLE
FatalThrowableError: Class 'Spatie\Mailcoach\Http\App\Queries\Filters\SendTypeFilter' not found

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#52]
I get this error when I visit /mailcoach/campaigns/3/outbox.

```
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Spatie\Mailcoach\Http\App\Queries\Filters\SendTypeFilter' not found
Level
ERROR
URL
https://myproject.com/mailcoach/campaigns/3/outbox
Input
[]
HTTP_REFERER
https://myproject.com/mailcoach/campaigns/3/summary

Trace
#0 /apps/myproject/releases/25/vendor/spatie/laravel-mailcoach/src/Http/App/Controllers/Campaigns/Sent/OutboxController.php(12): Spatie\Mailcoach\Http\App\Queries\CampaignSendsQuery->__construct()
#1 /apps/myproject/releases/25/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Spatie\Mailcoach\Http\App\Controllers\Campaigns\Sent\OutboxController->__invoke()
#2 /apps/myproject/releases/25/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
#3 /apps/myproject/releases/25/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#4 /apps/myproject/releases/25/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#5 /apps/myproject/releases/25/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 /apps/myproject/releases/25/vendor/spatie/laravel-mailcoach/src/Http/App/Middleware/SetMailcoachDefaults.php(17): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#7 /apps/myproject/releases/25/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Spatie\Mailcoach\Http\App\Middleware\SetMailcoachDefaults->handle()
#8 /apps/myproject/releases/25/vendor/spatie/laravel-mailcoach/src/Http/App/Middleware/Authorize.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 /apps/myproject/releases/25/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Spatie\Mailcoach\Http\App\Middleware\Authorize->handle()
#10 /apps/myproject/releases/25/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /apps/myproject/releases/25/vendor/spatie/laravel-mailcoach/src/Http/App/Middlew…
```

**Comment by freekmurze** [comment]
This has been fixed in the newly released `v1.6.4`
