### ISSUE TITLE
Error Exception: Use of undefined constant SIGTERM - assumed 'SIGTERM' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by fcaivano** [spatie/mailcoach-support#63]
```
ErrorException
Use of undefined constant SIGTERM - assumed 'SIGTERM' (this will throw an Error in a future version of PHP)
.com/settings/mail-configuration
```
_Illuminate\Foundation\Bootstrap\HandleExceptions::handleError:54
vendor/laravel/horizon/src/Console/TerminateCommand.php:54_

**Getting that exception when saving configuration.**

Using PHP 7.4. From DO, installed with forge and then the package using composer create-project...

The configuration get's saved anyways.

**Comment by freekmurze** [comment]
Could you post the entire stack trace of that error here?

**Comment by freekmurze** [comment]
This seems to be an error coming from laravel/horizon and is probably caused because of the `pcntl` extension that is missing. Could you verify it's available on your system?

**Comment by mattiasgeniar** [comment]
I have the same error, some troubleshooting:

```
$ php -m | grep -i pcntl
pcntl

$ php -v
PHP 7.4.2 (cli) (built: Feb  1 2020 17:49:29) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies
```

Full stacktrace:

```
==> laravel-2020-02-12.log <==
[2020-02-12 07:59:17] production.ERROR: Use of undefined constant SIGTERM - assumed 'SIGTERM' (this will throw an Error in a future version of PHP) {"userId":1,"exception":"[object] (ErrorException(code: 0): Use of undefined constant SIGTERM - assumed 'SIGTERM' (this will throw an Error in a future version of PHP) at /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/horizon/src/Console/TerminateCommand.php:54)
[stacktrace]
#0 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/horizon/src/Console/TerminateCommand.php(54): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Laravel\\Horizon\\Console\\TerminateCommand->handle()
#2 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#3 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#8 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#9 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#10 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/symfony/console/Application.php(1012): Illuminate\\Console\\Command->run()
#11 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand()
#12 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#13 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#14 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Console/Application.php(185): Illuminate\\Console\\Application->run()
#15 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(273): Illuminate\\Console\\Application->call()
#16 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Foundation\\Console\\Kernel->call()
#17 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/app/Http/App/Controllers/Settings/MailConfiguration/EditMailConfigurationController.php(20): Illuminate\\Support\\Facades\\Facade::__callStatic()
#18 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): App\\Http\\App\\Controllers\\Settings\\MailConfiguration\\EditMailConfigurationController->update()
#19 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#20 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#21 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#22 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#23 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#25 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#27 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#29 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#31 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#33 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#35 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#37 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#38 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#39 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#40 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#41 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#42 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#44 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#46 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#48 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#50 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#52 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#54 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#55 /var/www/html/newsletter.ma.ttias.be/releases/20200211-193905/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#56 {main}
```

phpinfo is available here (for now): https://newsletter.ma.ttias.be/phpinfo.php

It doesn't quite make any sense yet to me either, that constant should be available if the extension is loaded.

If I execute the command via CLI, it works.

```
$ php artisan horizon:terminate
Sending TERM Signal To Process: 3393
```

**Comment by freekmurze** [comment]
@fcaivano 

In `EditMailConfigurationController`, could you try replacing the line

```php
Artisan::call('horizon:terminate');
```

with

```php
dispatch(function () {
    Artisan::call('horizon:terminate');
});
```

And let me know if that works for you?

**Comment by mattiasgeniar** [comment]
Confirms this is the fix for me! No more notice anymore and horizon workers have cleanly restarted.

**Comment by riasvdv** [comment]
Fixed in https://github.com/spatie/Mailcoach/releases/tag/1.0.9
