### ISSUE TITLE
SQL SQLSTATE[42883] error on receiving AWS SES SNS webhook

### ISSUE THREAD

**Issue by hughgrigg** [spatie/mailcoach-support#90]
I'm seeing this error in the logs on receiving a webhook notification from SES via SNS:

```
SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text ->> unknown
LINE 1: ... as aggregate from \"webhook_calls\" where \"payload\"->>'Messag...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. at /home/mailcoach/mailcoach.mydomain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)
[stacktrace]
#0 /home/mailcoach/mailcoach.mydomain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(121): PDOStatement->execute()
#1 /home/mailcoach/mailcoach.mydomain.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(335): Doctrine\\DBAL\\Driver\\PDOStatement->execute()
#2 /home/mailcoach/mailcoach.mydomain.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#3 /home/mailcoach/mailcoach.mydomain.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#4 /home/mailcoach/mailcoach.mydomain.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run()
#5 /home/mailcoach/mailcoach.mydomain.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2149): Illuminate\\Database\\Connection->select()
#6 /home/mailcoach/mailcoach.mydomain.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2137): Illuminate\\Database\\Query\\Builder->runSelect()
#7 /home/mailcoach/mailcoach.mydomain.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2609): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#8 /home/mailcoach/mailcoach.mydomain.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2138): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#9 /home/mailcoach/mailcoach.mydomain.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2536): Illuminate\\Database\\Query\\Builder->get()
#10 /home/mailcoach/mailcoach.mydomain.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2475): Illuminate\\Database\\Query\\Builder->aggregate()
#11 /home/mailcoach/mailcoach.mydomain.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1366): Illuminate\\Database\\Query\\Builder->min()
#12 /home/mailcoach/mailcoach.mydomain.com/vendor/spatie/laravel-mailcoach-ses-feedback/src/SesWebhookCall.php(26): Illuminate\\Database\\Eloquent\\Builder->__call()
#13 /home/mailcoach/mailcoach.mydomain.com/vendor/spatie/laravel-mailcoach-ses-feedback/src/ProcessSesWebhookJob.php(30): Spatie\\MailcoachSesFeedback\\SesWebhookCall->isFirstOfThisSesMessage()
```

Seems to originate from `SesWebhookCall::isFirstOfThisSesMessage`:

```php
<?php

    public function isFirstOfThisSesMessage(): bool
    {
        $firstMessageId = (int) SesWebhookCall::where('payload->MessageId', $this->payload['MessageId'])->min('id');

        return $this->id === $firstMessageId;
    }
```

Specifically the `->` in the column name there.

**Comment by hughgrigg** [comment]
It looks like this is because Mailcoach actually requires MySQL, and this installation is using Postgres. Could it be made clearer in the docs that MySQL is required?

**Comment by hughgrigg** [comment]
Looks like it's this issue: https://github.com/laravel/framework/issues/31029

The `webhook_calls.payload` column is created as `text` when it should be `json`. I will see if I can raise a PR for this.

In the mean time, existing tables can be patched with this in PostgreSQL:

```sql
ALTER TABLE webhook_calls ALTER COLUMN payload TYPE JSON USING payload::JSON;
```

**Comment by hughgrigg** [comment]
PR to make `webhook_calls.payload` a JSON column instead of text is here https://github.com/spatie/Mailcoach/pull/16

**Comment by freekmurze** [comment]
The PR has been merged.
